apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: aug2025-poc
  labels:
    app: fastapi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: fastapi
          image: quay.io/rh-ee-csuryant/aug2025-poc/fastapi-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_USER
              value: devuser
            - name: DATABASE_PASSWORD
              value: openshift123
            - name: DATABASE_NAME
              value: pocdb
            - name: DATABASE_HOST
              value: postgresql
            - name: DATABASE_PORT
              value: "5432"

