apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: backend-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: backend-trigger
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.head_commit.message.contains('trigger-ci')"
      bindings:
        - ref: backend-trigger-binding
      template:
        ref: backend-trigger-template

