apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: backend-ci-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
        apiVersion: tekton.dev/v1
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-data

    - name: build-and-push
      runAfter: [clone]
      taskRef:
        name: buildah
        kind: ClusterTask
        apiVersion: tekton.dev/v1
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: CONTEXT
          value: $(workspaces.shared-data.path)
        - name: DOCKERFILE
          value: Dockerfile
      workspaces:
        - name: source
          workspace: shared-data

