apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: backend-trigger-binding
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: commit-message
      value: $(body.head_commit.message)

